x
apiVersion: v1
kind: Service
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: hello-python
    tier: hello-python
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-python
  labels:
    app: hello-python
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-python
        tier: hello-python
    spec:
      containers:
      - image: 127.0.0.1:30400/hello-python:$BUILD_TAG
        name: hello-python
        ports:
        - containerPort: 80
          name: hello-python
